[build]
builder = "nixpacks"

[deploy]
startCommand = "node scripts/railway-start.js"
healthcheckPath = "/api/ping" 
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PORT = { default = "5000" }