[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/ping"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[services]]
name = "hmo-property-search"

[services.variables]
NODE_ENV = "production"