[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm run start:production"
healthcheckPath = "/api/ping"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[[services]]
name = "hmo-property-search"

[services.variables]
NODE_ENV = "production"