[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && node railway-start.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[[services]]
name = "hmo-property-search"

[services.variables]
NODE_ENV = "production"